export { createAggregate } from "./lib/aggregate";
export { createEntity } from "./lib/entity";
export { createValueObject } from "./lib/value-object";
export { createBrandedId } from "./lib/branded-id";
export { createContainer, setPortAdapter, getPortAdapter } from "./lib/di.v2";
export { deepFreeze } from "./lib/utils";
export type { AggregateConfig } from "./lib/aggregate";
export type { EntityConfig } from "./lib/entity";
export type { ValueObjectConfig } from "./lib/value-object";
export type { BrandedIdConfig } from "./lib/branded-id";
export type { IDomainEvent } from "./lib/aggregate";
export { validateWithSchema } from "./lib/validation";
